# Generated by Django 4.0.3 on 2022-03-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyWeatherObject',
            new_name='DailyWeather',
        ),
    ]
